using ASTquizApp.Data;
using ASTquizApp.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;


namespace ASTquizApp.Services
{
    public class PdfService
    {

        public void CreateResultPdf(Result result)
        {

            string fileName =
                "Quiz_Result_"
                + result.CandidateName
                + ".pdf";

            Document.Create(container =>
            {
                container.Page(page =>
                {

                    page.Margin(50);

                    page.Header()
                    .Text("QUIZ TEST RESULT")
                    .FontSize(24)
                    .Bold();

                    page.Content()
                    .Column(column =>
                    {
                        column.Spacing(15);

                        column.Item()
                        .Text(
                        "Candidate: "
                        + result.CandidateName);

                        column.Item()
                        .Text(
                        "Percentage: "
                        + result.Percentage
                        .ToString("0.00")
                        + "%");

                        column.Item()
                        .LineHorizontal(1f, Unit.Point);

                        for (int i = 0; i < QuizData.Questions.Count; i++)
                        {

                            Question question =
                                QuizData.Questions[i];

                            string candidateAnswer =
                                QuizData.Answers.ContainsKey(i)
                                ?
                                QuizData.Answers[i]
                                :
                                "Not Attempted";

                            string candidateAnswerText =
                                GetAnswerText(
                                    question,
                                    candidateAnswer);

                            string correctAnswerText =
                                GetAnswerText(
                                    question,
                                    question.CorrectAnswer);

                            column.Item()
                            .Text(
                            "Question "
                            + (i + 1)

                            + "\n\nBook: "
                            + question.Book

                            + "\nChapter: "
                            + question.Chapter

                            + "\nTopic: "
                            + question.Topic

                            + "\n\n"
                            + question.QuestionText

                            + "\n\nA. "
                            + question.OptionA

                            + "\nB. "
                            + question.OptionB

                            + "\nC. "
                            + question.OptionC

                            + "\nD. "
                            + question.OptionD

                            + "\n\nCandidate Answer: "
                            + candidateAnswerText

                            + "\nCorrect Answer: "
                            + correctAnswerText

                            + "\nResult: "
                            + (
                                candidateAnswer ==
                                question.CorrectAnswer
                                ?
                                "CORRECT"
                                :
                                "WRONG"
                              )

                            );


                            column.Item()
                            .LineHorizontal(1f, Unit.Point);

                        }
                    });

                    page.Footer()
                    .AlignCenter()
                    .Text(
                    "Generated by AST Quiz App: Copyright © muhammmadali" + DateTime.Now.Year);

                });

            })
            .GeneratePdf(fileName);
        }
        private string GetAnswerText(
        Question question,
        string answer)
        {

            switch (answer)
            {
                case "A":
                    return "A. "
                    + question.OptionA;

                case "B":
                    return "B. "
                    + question.OptionB;

                case "C":
                    return "C. "
                    + question.OptionC;

                case "D":
                    return "D. "
                    + question.OptionD;

                default:
                    return "Not Attempted";

            }

        }

    }
}