using ASTquizApp.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;


namespace ASTquizApp.Services
{
    public class PdfService
    {

        public void CreateResultPdf(Result result)
        {

            string fileName =
                "Quiz_Result_"
                + result.CandidateName
                + ".pdf";

            Document.Create(container =>
            {
                container.Page(page =>
                {

                    page.Margin(50);

                    page.Header()
                    .Text("QUIZ TEST RESULT")
                    .FontSize(24)
                    .Bold();

                    page.Content()
                    .Column(column =>
                    {
                        column.Spacing(15);

                        column.Item()
                        .Text(
                        "Candidate Name: "
                        + result.CandidateName);

                        column.Item()
                        .Text(
                        "Date: "
                        + DateTime.Now.ToString(
                        "dd-MMM-yyyy HH:mm"));

                        column.Item()
                        .Text(
                        "Total Questions: "
                        + result.TotalQuestions);

                        column.Item()
                        .Text(
                        "Correct Answers: "
                        + result.CorrectAnswers);

                        column.Item()
                        .Text(
                        "Wrong Answers: "
                        + result.WrongAnswers);

                        column.Item()
                        .Text(
                        "Percentage: "
                        + result.Percentage
                        .ToString("0.00")
                        + "%");

                    });

                    page.Footer()
                    .AlignCenter()
                    .Text(
                    "Generated by AST Quiz App: Copyright © muhammmadali" + DateTime.Now.Year);

                });

            })
            .GeneratePdf(fileName);
        }
    }
}